//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9148
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;
using System.Xml.Serialization;
using System.Xml.Schema;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace DokumentyCyfrowe2
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("wniosek", Namespace = "", IsNullable = false)]
    public partial class typ_wniosku
    {

        private wnioskodawca_type wnioskodawcaField;

        private rodzina_wnioskodawcy_type rodzina_wnioskodawcyField;

        private string pouczenieField;

        private System.DateTime data_zlozeniaField;

        private bool data_zlozeniaFieldSpecified;

        public typ_wniosku()
        {
            this.pouczenieField = @"Wnoszę o przyznanie mi prawa do zamieszkania w Domach Studenckich PG.
         Oświadczam, iż zapoznałem się z Regulaminem przyznawania prawa do zamieszkania w Domach Studenckich Politechniki Gdańskiej.
         Oświadczam, że gospodarstwo domowe nie osiąga dochodów ze źródeł innych niż wskazane.
         Uprzedzony o odpowiedzialności karnej za przestępstwo wyłudzenia nienależnych świadczeń finansowych (art. 286 KK) oświadczam, że wykazane
         dane są kompletne i zgodne ze stanem faktycznym.
         Oświadczam, iż uprzedzono mnie, że w przypadku, gdy okaże się, że otrzywąłem/łam prawo do zamieszkania w Domu Studenckim PG na podstawie
         nieprawdziwych danych, będą wyciągnięte wobec mnie konsekwencje dyscyplinarne, do wydalenia z Uczelni włącznie, niezależnie od skutków cywilnoprawnych.";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wnioskodawca_type wnioskodawca
        {
            get
            {
                return this.wnioskodawcaField;
            }
            set
            {
                this.wnioskodawcaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rodzina_wnioskodawcy_type rodzina_wnioskodawcy
        {
            get
            {
                return this.rodzina_wnioskodawcyField;
            }
            set
            {
                this.rodzina_wnioskodawcyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pouczenie
        {
            get
            {
                return this.pouczenieField;
            }
            set
            {
                this.pouczenieField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime data_zlozenia
        {
            get
            {
                return this.data_zlozeniaField;
            }
            set
            {
                this.data_zlozeniaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool data_zlozeniaSpecified
        {
            get
            {
                return this.data_zlozeniaFieldSpecified;
            }
            set
            {
                this.data_zlozeniaFieldSpecified = value;
            }

        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wnioskodawca_type
    {

        private wydzial_type wydzialField;

        private string nr_albumuField;

        private string na_rok_akademickiField;

        private string nazwiskoField;

        private string imieField;

        private string przewidywany_sem_studiowField;

        private rodzaj_studiow_type rodzaj_studiowField;

        private kierunek_type kierunekField;

        private string emailField;

        private string telefonField;

        private adres_type adresField;

        private wojewodztwo_type wojewodztwoField;

        private string powiatField;

        private string gminaField;

        private string nr_ds_priorytet1Field;

        private string nr_ds_priorytet2Field;

        private malzonek_type malzonekField;

        private string praca_na_rzecz_uczelniField;

        private bool miejsce_dla_dzieckaField;

        private bool miejsce_dla_dzieckaFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wydzial_type wydzial
        {
            get
            {
                return this.wydzialField;
            }
            set
            {
                this.wydzialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string nr_albumu
        {
            get
            {
                return this.nr_albumuField;
            }
            set
            {
                this.nr_albumuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string na_rok_akademicki
        {
            get
            {
                return this.na_rok_akademickiField;
            }
            set
            {
                this.na_rok_akademickiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nazwisko
        {
            get
            {
                return this.nazwiskoField;
            }
            set
            {
                this.nazwiskoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imie
        {
            get
            {
                return this.imieField;
            }
            set
            {
                this.imieField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string przewidywany_sem_studiow
        {
            get
            {
                return this.przewidywany_sem_studiowField;
            }
            set
            {
                this.przewidywany_sem_studiowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public rodzaj_studiow_type rodzaj_studiow
        {
            get
            {
                return this.rodzaj_studiowField;
            }
            set
            {
                this.rodzaj_studiowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kierunek_type kierunek
        {
            get
            {
                return this.kierunekField;
            }
            set
            {
                this.kierunekField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefon
        {
            get
            {
                return this.telefonField;
            }
            set
            {
                this.telefonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public adres_type adres
        {
            get
            {
                return this.adresField;
            }
            set
            {
                this.adresField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wojewodztwo_type wojewodztwo
        {
            get
            {
                return this.wojewodztwoField;
            }
            set
            {
                this.wojewodztwoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string powiat
        {
            get
            {
                return this.powiatField;
            }
            set
            {
                this.powiatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gmina
        {
            get
            {
                return this.gminaField;
            }
            set
            {
                this.gminaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string nr_ds_priorytet1
        {
            get
            {
                return this.nr_ds_priorytet1Field;
            }
            set
            {
                this.nr_ds_priorytet1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string nr_ds_priorytet2
        {
            get
            {
                return this.nr_ds_priorytet2Field;
            }
            set
            {
                this.nr_ds_priorytet2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public malzonek_type malzonek
        {
            get
            {
                return this.malzonekField;
            }
            set
            {
                this.malzonekField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string praca_na_rzecz_uczelni
        {
            get
            {
                return this.praca_na_rzecz_uczelniField;
            }
            set
            {
                this.praca_na_rzecz_uczelniField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool miejsce_dla_dziecka
        {
            get
            {
                return this.miejsce_dla_dzieckaField;
            }
            set
            {
                this.miejsce_dla_dzieckaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool miejsce_dla_dzieckaSpecified
        {
            get
            {
                return this.miejsce_dla_dzieckaFieldSpecified;
            }
            set
            {
                this.miejsce_dla_dzieckaFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum wydzial_type
    {

        /// <remarks/>
        ARCH,

        /// <remarks/>
        CHEM,

        /// <remarks/>
        ETI,

        /// <remarks/>
        EIA,

        /// <remarks/>
        FTIMS,

        /// <remarks/>
        ILIŚ,

        /// <remarks/>
        MECH,

        /// <remarks/>
        OIO,

        /// <remarks/>
        ZIE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum rodzaj_studiow_type
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("I stopnia")]
        Istopnia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("II stopnia")]
        IIstopnia,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum kierunek_type
    {

        /// <remarks/>
        Architektura,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Gospodarka przestrzenna")]
        Gospodarkaprzestrzenna,

        /// <remarks/>
        Biotechnologia,

        /// <remarks/>
        Chemia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Chemia budowlana")]
        Chemiabudowlana,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inżynieria i technologie nośników energii")]
        Inżynieriaitechnologienośnikówenergii,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inżynieria materiałowa")]
        Inżynieriamateriałowa,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Konserwacja i degradacja materiałów")]
        Konserwacjaidegradacjamateriałów,

        /// <remarks/>
        Korozja,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Technologia chemiczna")]
        Technologiachemiczna,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Zielone technologie i monitoring")]
        Zielonetechnologieimonitoring,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Automatyka i robotyka")]
        Automatykairobotyka,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Elektronika i telekomunikacja")]
        Elektronikaitelekomunikacja,

        /// <remarks/>
        Informatyka,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inżynieria biomedyczna")]
        Inżynieriabiomedyczna,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inżynieria danych")]
        Inżynieriadanych,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Technologie kosmiczne i satelitarne")]
        Technologiekosmiczneisatelitarne,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Automatyka i robotyka")]
        Automatykairobotyka1,

        /// <remarks/>
        Elektrotechnika,

        /// <remarks/>
        Energetyka,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Fizyka techniczna")]
        Fizykatechniczna,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inżynieria materiałowa")]
        Inżynieriamateriałowa1,

        /// <remarks/>
        Matematyka,

        /// <remarks/>
        Nanotechnologia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Podstawy nauk technicznych")]
        Podstawynauktechnicznych,

        /// <remarks/>
        Budownictwo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Geodezja i kartografia")]
        Geodezjaikartografia,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inżynieria środowiska")]
        Inżynieriaśrodowiska,

        /// <remarks/>
        Transport,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Techniki geodezyjne w inżynierii")]
        Technikigeodezyjnewinżynierii,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Energetyka")]
        Energetyka1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Inżynieria mechaniczno-medyczna")]
        Inżynieriamechanicznomedyczna,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mechanika i budowa maszyn")]
        Mechanikaibudowamaszyn,

        /// <remarks/>
        Mechatronika,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Zarządzanie i inżynieria produkcji")]
        Zarządzanieiinżynieriaprodukcji,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Energetyka")]
        Energetyka2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Transport")]
        Transport1,

        /// <remarks/>
        Oceanotechnika,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Techniki geodezyjne w inżynierii")]
        Technikigeodezyjnewinżynierii1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Analityka gospodarcza")]
        Analitykagospodarcza,

        /// <remarks/>
        Ekonomia,

        /// <remarks/>
        Europeistyka,

        /// <remarks/>
        Zarządzanie,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Zarządzanie inżynierskie")]
        Zarządzanieinżynierskie,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class adres_type
    {

        private string ulicaField;

        private string nrField;

        private string kod_pocztowyField;

        private string miejscowoscField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "positiveInteger")]
        public string nr
        {
            get
            {
                return this.nrField;
            }
            set
            {
                this.nrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kod_pocztowy
        {
            get
            {
                return this.kod_pocztowyField;
            }
            set
            {
                this.kod_pocztowyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string miejscowosc
        {
            get
            {
                return this.miejscowoscField;
            }
            set
            {
                this.miejscowoscField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class czlonek_rodziny_type
    {

        private string nazwiskoField;

        private string imieField;

        private string wiekField;

        private string st_pokrewienstwaField;

        private string status_zatrudnieniaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nazwisko
        {
            get
            {
                return this.nazwiskoField;
            }
            set
            {
                this.nazwiskoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imie
        {
            get
            {
                return this.imieField;
            }
            set
            {
                this.imieField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "positiveInteger")]
        public string wiek
        {
            get
            {
                return this.wiekField;
            }
            set
            {
                this.wiekField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string st_pokrewienstwa
        {
            get
            {
                return this.st_pokrewienstwaField;
            }
            set
            {
                this.st_pokrewienstwaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status_zatrudnienia
        {
            get
            {
                return this.status_zatrudnieniaField;
            }
            set
            {
                this.status_zatrudnieniaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rodzina_wnioskodawcy_type
    {

        private czlonek_rodziny_type[] czlonek_rodzinyField;

        private bool dochod_utraconyField;

        private bool dochod_utraconyFieldSpecified;

        private bool dochod_uzyskanyField;

        private bool dochod_uzyskanyFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("czlonek_rodziny", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public czlonek_rodziny_type[] czlonek_rodziny
        {
            get
            {
                return this.czlonek_rodzinyField;
            }
            set
            {
                this.czlonek_rodzinyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dochod_utracony
        {
            get
            {
                return this.dochod_utraconyField;
            }
            set
            {
                this.dochod_utraconyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dochod_utraconySpecified
        {
            get
            {
                return this.dochod_utraconyFieldSpecified;
            }
            set
            {
                this.dochod_utraconyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dochod_uzyskany
        {
            get
            {
                return this.dochod_uzyskanyField;
            }
            set
            {
                this.dochod_uzyskanyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dochod_uzyskanySpecified
        {
            get
            {
                return this.dochod_uzyskanyFieldSpecified;
            }
            set
            {
                this.dochod_uzyskanyFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class malzonek_type
    {

        private string imie_i_nazwiskoField;

        private status_malzonka_type statusField;

        private bool miejsce_dlaField;

        private bool miejsce_dlaFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imie_i_nazwisko
        {
            get
            {
                return this.imie_i_nazwiskoField;
            }
            set
            {
                this.imie_i_nazwiskoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public status_malzonka_type status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool miejsce_dla
        {
            get
            {
                return this.miejsce_dlaField;
            }
            set
            {
                this.miejsce_dlaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool miejsce_dlaSpecified
        {
            get
            {
                return this.miejsce_dlaFieldSpecified;
            }
            set
            {
                this.miejsce_dlaFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum status_malzonka_type
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("STUDENTEM PG")]
        STUDENTEMPG,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("STUDENT INNEJ UCZELNI")]
        STUDENTINNEJUCZELNI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NIE JEST STUDENTEM")]
        NIEJESTSTUDENTEM,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum wojewodztwo_type
    {

        /// <remarks/>
        dolnoslaskie,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("kujawsko-pomorskie")]
        kujawskopomorskie,

        /// <remarks/>
        lubelskie,

        /// <remarks/>
        lubuskie,

        /// <remarks/>
        lodzkie,

        /// <remarks/>
        malopolskie,

        /// <remarks/>
        mazowieckie,

        /// <remarks/>
        opolskie,

        /// <remarks/>
        podkarpackie,

        /// <remarks/>
        podlaskie,

        /// <remarks/>
        pomorskie,

        /// <remarks/>
        slaskie,

        /// <remarks/>
        swietokrzyskie,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("warminsko-mazurskie")]
        warminskomazurskie,

        /// <remarks/>
        wielkopolskie,

        /// <remarks/>
        zachodniopomorskie,
    }
}